[package]
name = "pipe-cli"
version = "0.3.0"
authors = ["Annie Ehler <annie.ehler.4@gmail.com>"]
edition = "2024"
description = "A simple command line tool to pipe data between commands"
documentation = "https://github.com/annie444/piped"
readme = "README.md"
homepage = "https://github.com/annie444/piped"
repository = "https://github.com/annie444/piped"
license = "MIT"
keywords = ["pipe", "cli", "command-line", "data-piping"]
categories = ["command-line-utilities", "text-processing"]
build = "build.rs"
autolib = false
autobins = false

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-v{ version }-{ target }{ archive-suffix }"
bin-dir = "{ name }-v{ version }-{ target }/{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[[bin]]
name = "pipe"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6", features = ["derive"] }
shlex = "2.0"
sysinfo = "0.39"

[build-dependencies]
clap = { version = "4.6", features = ["derive"] }
clap_mangen = "0.3"
